services:
  apache:
    image: httpd:latest
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    volumes:
      - ./site80:/usr/local/apache2/htdocs/site80
      - ./site81:/usr/local/apache2/htdocs/site81
      - ./site82:/usr/local/apache2/htdocs/site82
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
