services:
  android:
    image: budtmo/docker-android:emulator_14.0
    ports:
      - 6080:6080
    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: true
    # devices:
    #   - ./dev/kvm:/dev/kvm
