volumes:
  database_volume:
  cloudbeaver_volume:

networks:
  main_network:

services:
  database:
    build: ./database
    environment:
      MARIADB_ROOT_PASSWORD: app
      MARIADB_PASSWORD: app
      MARIADB_USER: app
    ports:
      - 3306:3306
    volumes:
      - ./database/entrypoint.sql:/docker-entrypoint-initdb.d/entrypoint.sql

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000

  dbmanager:
    image: dbeaver/cloudbeaver
    volumes:
      - cloudbeaver_volume:/opt/cloudbeaver/workspace
    ports:
      - 3307:8978

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/app:/app
    ports:
      - 3010:3000

  waha:
    build: ./waha/
    ports:
      - 3000:3000
    volumes:
      - ./waha/.sessions:/app/.sessions
