services:
  waha:
    build: ./waha/
    ports:
      - 3000:3000
    volumes:
      - ./waha/.sessions:/app/.sessions
    # environment:
    #   WAHA_APPS_ENABLED: true
    #   WAHA_API_KEY: abcde

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/app:/app
    ports:
      - 3010:3000

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000