services:
  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kestra/tmp:/tmp
    command: server local
