#!/bin/sh
reset

prefix=$1
root_dir=$(pwd)
compose_yml="$root_dir/app/$prefix/compose.yml"

# sh $file_run
# cd $file_run && docker compose up -d --build --force-recreate --remove-orphans

docker compose --profile "*" stop
docker compose -f "$compose_yml" up -d --build --force-recreate --remove-orphans