services:
  electronjs:
    image: electronjs
    build: ./electron
    environment:
      DISPLAY: ${DISPLAY}
      # ELECTRON_DISABLE_SECURITY_WARNINGS: false
    volumes:
      - ./electron/app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
