volumes:
  caddy_data:
  caddy_config:

services:
  php:
    image: dunglas/frankenphp
    build: .
    working_dir: /apps/laravel
    ports:
      - "80:80" # HTTP
      - "81:81" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./frankenphp/caddy:/etc/caddy
      - ./laravel:/apps/laravel
      - ./site81:/apps/site81
    environment:
      - LARAVEL_STORAGE_PATH=/apps/laravel/storage
