networks:
  mysql-network:

services:
  # curl -sL https://raw.githubusercontent.com/jeff-silva/howto/refs/heads/main/.bin/nestjs-install.sh | bash
  nestjs:
    build: ./nestjs/.docker
    working_dir: /app
    command: bash -c "yarn install && yarn run start:dev"
    ports:
      - 3000:3000
    volumes:
      - ./nestjs:/app
    networks:
      - mysql-network

  # curl -sL https://raw.githubusercontent.com/jeff-silva/howto/refs/heads/main/.bin/nuxt-install.sh | bash
  nuxt3:
    image: node:18.16.0
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3001:3001
    volumes:
      - ./nuxt3:/app

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_ROOT_HOST: "%"
    networks:
      - mysql-network

  mysql-pma:
    image: phpmyadmin
    ports:
      - "3307:80"
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: app
      PMA_PASSWORD: app
    networks:
      - mysql-network
