services:
  # curl -sL https://raw.githubusercontent.com/jeff-silva/howto/refs/heads/main/.bin/nestjs-install.sh | bash
  nestjs:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn run start"
    ports:
      - 3000:3000
    volumes:
      - ./nestjs:/app
