services:
  # # docker run --rm -it -v $(pwd):/app -w /app node:18 npx nuxi@latest init nuxt3
  # nuxt3:
  #   image: node:22
  #   working_dir: /app
  #   command: bash -c "yarn install && yarn dev"
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./nuxt3:/app

  capacitor:
    build: ./.docker/capacitor
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./nuxt3:/app
