services:
  # docker run --rm -it -v $(pwd):/app -w /app node:18 npx nuxi@latest init nuxt3
  nuxt3:
    build: ./nuxt3/.docker
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./nuxt3:/app
