name: howto

networks:
  default:
    name: main_network

include:
  - ../.services/npm/compose.yml
  - ../.services/homeassistant/compose.yml
  - ../.services/supabase/compose.yml
  - ../.services/romm/compose.yml
