networks:
  main_network:
    driver: bridge

volumes:
  rabbitmq_data:

services:
  keycloak:
    build: ./keycloak
    working_dir: /opt/keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: main@grr.la
      KC_BOOTSTRAP_ADMIN_PASSWORD: main@grr.la
      KK_TO_RMQ_URL: localhost
      KK_TO_RMQ_PORT: 5672
      # KK_TO_RMQ_VHOST:
      KK_TO_RMQ_EXCHANGE: amq.topic
      KK_TO_RMQ_USERNAME: main
      KK_TO_RMQ_PASSWORD: main
      KK_TO_RMQ_USE_TLS: false
      # KK_TO_RMQ_KEY_STORE:
      # KK_TO_RMQ_KEY_STORE_PASS:
      # KK_TO_RMQ_TRUST_STORE:
      # KK_TO_RMQ_TRUST_STORE_PASS:
    ports:
      - 8080:8080
    networks:
      - main_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672" # Porta AMQP
      - "15672:15672" # Porta de gerenciamento
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistir dados do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: main
      RABBITMQ_DEFAULT_PASS: main
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - main_network

  backend:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    networks:
      - main_network
    depends_on:
      - rabbitmq
