volumes:
  redis_data:

services:
  service-redis:
    image: redis:alpine
    restart: unless-stopped
    expose: [6379]
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
