networks:
  mysql-network:

services:
  adonisjs:
    image: node:22
    working_dir: /app
    command: bash -c "npm run build && cp .env build/.env && cd build && npm run start"
    environment:
      NODE_ENV: production
    ports:
      - 3333:3333
    volumes:
      - ./adonisjs:/app
    networks:
      - mysql-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_ROOT_HOST: "%"
    networks:
      - mysql-network
