networks:
  mysql-network:

services:
  adonisjs:
    image: node:22
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    ports:
      - 3333:3333
    volumes:
      - ./adonisjs:/app
    networks:
      - mysql-network
    depends_on:
      - mysql

  # bash <(curl -s "https://raw.githubusercontent.com/jeff-silva/howto/refs/heads/main/.bin/nuxt-install.sh")
  nuxt3:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./nuxt3:/app

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_ROOT_HOST: "%"
    networks:
      - mysql-network
