services:
  # # docker run --rm -it -v $(pwd):/app -w /app node:18 npx nuxi@latest init nuxt3
  # nuxt3:
  #   image: node:22
  #   working_dir: /app
  #   command: bash -c "yarn install && yarn dev"
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./nuxt3:/app

  # cd ./laravel-dir
  # docker run --rm -it -v ${PWD}/laravel:/app composer create-project laravel/laravel . && php artisan install:api

  # apache-php:
  #   build: ./apache-test
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./laravel:/var/www/html

  laravel:
    image: bitnami/laravel:latest
    volumes:
      - ./laravel:/app
    ports:
      - 8000:8000
