services:
  # https://docs.sftpgo.com/2.6/config-file/
  # https://github.com/drakkan/sftpgo/blob/2.6.x/sftpgo.json
  sftpgo:
    image: drakkan/sftpgo:latest
    ports:
      - "2121:2121"
      - "2222:2222"
      - "2280:2280"
      - "10080:10080"
    volumes:
      - sftpgodata:/srv/sftpgo
      - sftpgohome:/var/lib/sftpgo
    environment:
      - SFTPGO_FTPD__BINDINGS__0__PORT=2121
      - SFTPGO_SFTPD__BINDINGS__0__PORT=2222
      - SFTPGO_HTTPD__BINDINGS__0__PORT=2280
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
volumes:
  sftpgodata:
  sftpgohome:
