volumes:
  mongodb_data_volume:
  caddy_data_volume:
  caddy_config_volume:

services:
  caddy:
    image: caddy:latest
    working_dir: /app
    ports:
      - "443:443"
      - "443:443/udp"
      - "8000:8000"
      - "8010:8010"
      - "8020:8020"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data_volume:/data
      - caddy_config_volume:/config
    depends_on:
      - nestjs

  # port=3000
  nestjs:
    build: ./nestjs
    volumes:
      - ./nestjs/app:/app
    depends_on:
      - mongo
    links:
      - mongo

  # port=27017
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongodb_data_volume:/data/db

  # port=8081
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: app
      ME_CONFIG_BASICAUTH_PASSWORD: app
      ME_CONFIG_MONGODB_ADMINUSERNAME: app
      ME_CONFIG_MONGODB_ADMINPASSWORD: app
      ME_CONFIG_MONGODB_URL: mongodb://app:app@mongo:27017
    depends_on:
      - mongo

  # port=3000
  nuxt3:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    volumes:
      - ./nuxt3/app:/app
