services:
  # Default login:
  # email:     admin@example.com
  # password:  changeme
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      # - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
