services:
  # Default login:
  # email:     admin@example.com
  # password:  changeme
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "443:443"
      - "80-89:80-89"
    volumes:
      - ./public:/var/www/html
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
