services:
  # docker run --rm -it -v /home/jeff/howto/algorithm:/app -w /app node:18 npx nuxi@latest init nuxt3
  nuxt3:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./nuxt3:/app
