services:
  # docker run --rm -it -v $(pwd):/app -w /app node:18 npx nuxi@latest init nuxt3
  frontend:
    image: node:18.16.0
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/app
