services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes: [./backend/src:/app/src]

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/next.config.mjs:/app/next.config.mjs
