version: "3.8"

services:
  backend:
    build: ./backend
    ports: ["3000:3000"]
    volumes:
      - ./backend/project:/app
    environment:
      NODE_ENV: development
    command: bun run dev

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elysia_db
    ports: ["5432:5432"]
    volumes:
      - pgdata_volume:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/project:/var/lib/rabbitmq

volumes:
  pgdata_volume:
