# volumes:
#   database_volume:
#     driver: local
#   cloudbeaver_volume:

networks:
  main_network:

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - main_network

  database:
    build: ./database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app
    volumes:
      - ./database/.volume:/data/db
    networks:
      - main_network

  dbmanager:
    # build: ./dbmanager
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: app
      ME_CONFIG_MONGODB_ADMINPASSWORD: app
      ME_CONFIG_BASICAUTH_USERNAME: app
      ME_CONFIG_BASICAUTH_PASSWORD: app
      ME_CONFIG_MONGODB_URL: mongodb://app:app@database:27017/admin
    depends_on:
      - database
    networks:
      - main_network
