# volumes:
#   database_volume:
#     driver: local
#   cloudbeaver_volume:

networks:
  main_network:

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database
    networks:
      - main_network

  database:
    build: ./database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app
    volumes:
      - ./database/.volume:/data/db
    networks:
      - main_network

  dbmanager:
    # build: ./dbmanager
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: app
      ME_CONFIG_MONGODB_ADMINPASSWORD: app
      ME_CONFIG_BASICAUTH_USERNAME: app
      ME_CONFIG_BASICAUTH_PASSWORD: app
      ME_CONFIG_MONGODB_URL: mongodb://app:app@database:27017/admin
    depends_on:
      - database
    networks:
      - main_network

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/app:/app
    ports:
      - 3000:3000

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
      MINIO_DEFAULT_BUCKETS: app
    volumes:
      - ./minio/.data:/data
    networks:
      - main_network
