services:
  # 1) Create Django project in /python folder
  # docker run --rm -it -v ${PWD}/python:/app -w /app python:3.8 bash
  # pip install django
  # django-admin startproject src .
  #
  # 2) Close bash then init Django
  # docker compose up --build --force-recreate --remove-orphans
  python:
    image: python:3.8
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./python:/app
